name: application_weather
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  geocoding: ^3.0.0
  geolocator: ^13.0.4
  get: ^4.7.2
  http: ^1.3.0
  intl: ^0.20.2
  sleek_circular_slider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
